add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$dotnet\
$python
$character
"""

[directory]
style = "bold #cba6f7"
truncation_length = 4
truncate_to_repo = false

[git_branch]
symbol = " "
style = "bold #a6e3a1"

[git_status]
style = "bold #f9e2af"

[nodejs]
symbol = "󰎙 "
style = "bold #89b4fa"

[dotnet]
symbol = "󰪮 "
style = "bold #cba6f7"

[python]
symbol = "󰌠 "
style = "bold #f9e2af"

[character]
success_symbol = "[❯](bold #cba6f7)"
error_symbol = "[❯](bold #f38ba8)"
