-------------
# Fuente
# -------------------------

font_family JetBrainsMono Nerd Font
font_size 11.0

# -------------------------
# Ventana
# -------------------------

background_opacity 0.92
window_padding_width 12

hide_window_decorations yes

confirm_os_window_close 0

enable_audio_bell no

cursor_shape beam
cursor_blink_interval 0

# -------------------------
# Tabs
# -------------------------

tab_bar_style hidden

# -------------------------
# Catppuccin Mocha
# -------------------------

background            #1e1e2e
foreground            #cdd6f4

selection_background  #f5e0dc
selection_foreground  #1e1e2e

cursor                #cba6f7
cursor_text_color     #1e1e2e

url_color             #89dceb

active_border_color   #cba6f7
inactive_border_color #313244

# -------------------------
# ANSI
# -------------------------

color0  #45475a
color8  #585b70

color1  #f38ba8
color9  #f38ba8

color2  #a6e3a1
color10 #a6e3a1

color3  #f9e2af
color11 #f9e2af

color4  #89b4fa
color12 #89b4fa

color5  #cba6f7
color13 #cba6f7

color6  #89dceb
color14 #89dceb

color7  #bac2de
color15 #a6adc8
